[build]
command = "npm ci && npm run build"
publish = "build/client"

# Environment variables for production
[build.environment]
NODE_ENV = "production"
SESSION_SECRET = "d366d21f0ce32b45cf2bead6ef71e538c0e74dc28dbf084e9044ada82243e5f7"

[dev]
command = "npm run dev"
framework = "vite"

[template]
required-extensions = ["supabase"]