[build]
command = "npm ci && npm run build"
publish = "build/client"

# Environment variables for production
[build.environment]
NODE_ENV = "production"

[dev]
command = "npm run dev"
framework = "vite"

[template]
required-extensions = ["supabase"]